###Get all paintings
GET https://{{host}}:{{port}}/paintings
Accept: application/json

> {%
client.test("Get all paintings request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###Get painting with id 3
GET https://{{host}}:{{port}}/paintings/1
Accept: application/json

> {%
client.test("Get one painting request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###Post a painting
POST https://{{host}}:{{port}}/paintings
Accept: application/json

{
        "id" : 1,
        "name": "starry night",
        "artist_name": "van gogh",
        "year_of_origin": 1969,
        "current_price": 6969,
        "end_date": "2021-12-02"
}

> {%

 %}